# This workflow will run tests, build, and then publish a package to GitHub Packages when a release is created

name: Publish Tailwind Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx --no-install nx test tailwind
      - run: npx --no-install nx build tailwind

      - uses: actions/upload-artifact@v4
        with:
          name: tailwind
          path: ./dist/libs/tailwind
          if-no-files-found: ignore
          overwrite: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_artifact
        with:
          name: 'tailwind'
      - if: "${{ steps.check_artifact.outputs.exists == 'false' }}"
        run: |
          echo "::notice::Artifact not found"
          exit 0

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          name: tailwind
          path: ./dist/libs/tailwind

      - run: npm publish
        working-directory: dist/libs/tailwind
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
