# This workflow will run build, then publish a package to GitHub Packages when a tag is pushed

name: Publish Tailwind Package

on:
  push:
    tags: ['tailwind-v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx nx build tailwind --skip-nx-cache

      - uses: actions/upload-artifact@v4
        with:
          name: tailwind
          path: ./dist/libs/tailwind
          if-no-files-found: ignore
          overwrite: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_artifact
        with:
          name: 'tailwind'
      - run: |
          echo "::notice::Artifact not found"
          exit 0
        if: "${{ steps.check_artifact.outputs.exists == 'false' }}"

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          name: tailwind
          path: ./dist/libs/tailwind

      - run: npm publish
        working-directory: dist/libs/tailwind
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
